### ISSUE TITLE
Span is only forwarding error log records to  agent

### ISSUE THREAD

**Issue by andrewweston** [instana/go-sensor#244]
The `sendOpenTracingLogRecords` method in `span.go` is excluding log records that are not errors when forwarding log records to the agent.
We would like this filter removed so we can send other types of log records (info and warning) to Instana. If it makes sense I can create a PR with the proposed change.

**Comment by andrewslotin** [comment]
Hi @andrewweston! The current behaviour is intentional and we don't recommend using Instana tracer as a logging solution, since it makes application data noisy and hard to use to track down performance issues. Therefore it's unlikely that a change to collect info logs will be accepted.

However, I believe it would make a lot of sense to collect warning messages, since they are often related to performance issues. The OpenTracing logging API does not provide a way to set the level for a log message, so for initial implementation we went with the error message format used by our instrumentations. Please feel free to propose your solution for warning message handling!

**Comment by andrewweston** [comment]
@andrewslotin Thank you. I did find a way to get warning messages appearing as warnings in Instana by setting the tag key to "log.level" and tag value to "WARN".
